In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn import metrics

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [5]:
class AuthorClassifier:

    def stat(self, labelst, labelsp):
        print("--------------------------------------------------")
        print("STATISTICS")
        print("Accuracy:",metrics.accuracy_score(labelst, labelsp))
        print("Confusion matrix:\n",metrics.confusion_matrix(labelst, labelsp))

    def prep(self, trainData):
        trainData = np.delete(trainData, 0, axis=0) 
        trainData = np.delete(trainData, 0, axis=1) 
        # print("train Data shape", trainData.shape)
        txt = trainData[:,0]
        # print("text shape", txt.shape)
        txt = txt.reshape(txt.shape[0])
        y = trainData[:,1]
        y = y.reshape(len(y), 1)
        # print("text ", txt[0])
        vectorizer  = TfidfVectorizer(smooth_idf=False, sublinear_tf=False, norm=None, analyzer='word', stop_words = 'english')
        txt_fitted = vectorizer.fit(txt)
        x = txt_fitted.transform(txt)
        # x = x.todense()
        #x = np.array(x)
        #x = x.astype(np.float)
        # print("2 ", x.shape)
        # print("3 ", y.shape )

        svd = TruncatedSVD(n_components=100)
        xPCA = svd.fit_transform(x)
        # print("PCA reduced shape ",xPCA.shape)
        return xPCA, y

    def train(self, DataFile,kernel, c):
        with open(DataFile,'r') as fD:
            readerD = csv.reader(fD)
            trnData = np.array(list(readerD))
            np.random.shuffle(trnData)
            x,y = self.prep(trnData)
            xTest = x[0:100]
            xTrain = x[100:]
            yTest = y[0:100]
            yTrain = y[100:]
            print("prep done ")
            subclf = svm.SVC(kernel=kernel, C=c)
            subclf.fit(xTrain,yTrain)
            print("fit done")
            yPredict = subclf.predict(xTest)
            # print("predicted length:",len(yPredict))

            self.stat(yTest, yPredict)

For the linear SVM, we are using different values of C. The best result is coming for c = 0.01 

In [6]:
auth_classifier = AuthorClassifier()
auth_classifier.train('./Question-5/Train(1).csv','linear',0.001)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.6
Confusion matrix:
 [[35  3  6]
 [13 11  2]
 [15  1 14]]


In [7]:
auth_classifier.train('./Question-5/Train(1).csv','linear',0.01)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.72
Confusion matrix:
 [[39  4  3]
 [ 8  8  4]
 [ 7  2 25]]


In [8]:
auth_classifier.train('./Question-5/Train(1).csv','linear',0.1)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.66
Confusion matrix:
 [[32  2  6]
 [10 17  2]
 [11  3 17]]


For different kernel values, we are running the data. The best result is coming for kernel = linear for the given data.

In [9]:
auth_classifier.train('./Question-5/Train(1).csv','poly',0.01)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.44
Confusion matrix:
 [[42  1  0]
 [27  0  1]
 [27  0  2]]


In [10]:
auth_classifier.train('./Question-5/Train(1).csv','rbf',0.01)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.32
Confusion matrix:
 [[31  0  0]
 [28  0  0]
 [40  0  1]]


In [11]:
auth_classifier.train('./Question-5/Train(1).csv','sigmoid',0.01)

prep done 


/home/subbu/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


fit done
--------------------------------------------------
STATISTICS
Accuracy: 0.54
Confusion matrix:
 [[42  0  0]
 [14  4  0]
 [31  1  8]]
